### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [1]:
pip install torch

    100% |████████████████████████████████| 108.8MB 442kB/s ta 0:00:011   12% |████                            | 13.6MB 5.0MB/s eta 0:00:19
  Using cached https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Note: you may need to restart the kernel to use updated packages.


In [2]:
# Import torch and other required modules
import torch
import numpy as np

In [3]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [4]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - *your function to illustrate*

In [23]:
# Example 1 - ### your explanation ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]]])
b = torch.tensor([[[2, 4, 6], [3, 4, 5]]])
t_div1 = a + b
print(t_div1.shape)
t_div1

torch.Size([1, 2, 3])


tensor([[[ 3,  6,  9],
         [ 6,  8, 10]]])

In [24]:
# Example 2 - ### your explanation ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]]])
b = torch.tensor([[[2, 4, 6], [3, 4, 5]]])
t_div1 = a - b
print(t_div1.shape)
t_div1

torch.Size([1, 2, 3])


tensor([[[-1, -2, -3],
         [ 0,  0,  0]]])

### Function 2 - your function to illustrate

In [21]:
# Example 1 - ### your explanation ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]]])
b = torch.tensor([[[2, 4, 6], [3, 4, 5]]])
t_div1 = a / b
print(t_div1.shape)
t_div1

torch.Size([1, 2, 3])


tensor([[[0.5000, 0.5000, 0.5000],
         [1.0000, 1.0000, 1.0000]]])

In [22]:
# Example 2 - ### your explanation ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]]])
b = torch.tensor([[[2, 4, 6], [3, 4, 5]]])
t_mul1 = a * b
print(t_mul1.shape)
t_mul1

torch.Size([1, 2, 3])


tensor([[[ 2,  8, 18],
         [ 9, 16, 25]]])

### Function 3 - your function to illustrate

In [13]:
# Example 1 - ### your explanation ###
# 調換tensor維度
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],[[11, 22, 33], [44, 55, 66]]])
a.permute((2, 1, 0))


tensor([[[ 1, 11],
         [ 3, 44]],

        [[ 2, 22],
         [ 4, 55]],

        [[ 3, 33],
         [ 5, 66]]])

In [16]:
# Example 2 - ### your explanation ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],[[11, 22, 33], [44, 55, 66]]])
print(a)
a.transpose(1,2)


tensor([[[ 1,  2,  3],
         [ 3,  4,  5]],

        [[11, 22, 33],
         [44, 55, 66]]])


tensor([[[ 1,  3],
         [ 2,  4],
         [ 3,  5]],

        [[11, 44],
         [22, 55],
         [33, 66]]])

### Function 4 - your function to illustrate

In [7]:
# Example 1 - ### your explanation ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]]])
print(a.shape)
print(a)
a.reshape(1,6)

torch.Size([1, 2, 3])
tensor([[[1, 2, 3],
         [3, 4, 5]]])


tensor([[1, 2, 3, 3, 4, 5]])

In [8]:
# Example 2 - ### your explanation ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]]])
print(a.shape)
print(a)
a.view(1,6)

torch.Size([1, 2, 3])
tensor([[[1, 2, 3],
         [3, 4, 5]]])


tensor([[1, 2, 3, 3, 4, 5]])